apiVersion: vendir.k14s.io/v1alpha1
kind: Config
directories:
- path: vendor
  contents:
  - path: ingress-nginx
    git:
      url: https://github.com/kubernetes/ingress-nginx
      ref: helm-chart-4.14.1
      depth: 1
    includePaths:
    - charts/ingress-nginx/**/*
    excludePaths:
    - charts/ingress-nginx/OWNERS
    - charts/ingress-nginx/changelog/*
    newRootPath: charts/ingress-nginx
- path: helm/ingress-nginx
  contents:
    - path: .
      directory:
        path: vendor/ingress-nginx
      ignorePaths:
      - .kube-linter.yaml
      - Chart.yaml
      - values.schema.json
