apiVersion: vendir.k14s.io/v1alpha1
kind: Config
directories:
- path: helm
  contents:
  - path: ingress-nginx
    git:
      url: https://github.com/giantswarm/ingress-nginx-upstream
      ref: release-1.13
      depth: 1
    excludePaths:
    - charts/ingress-nginx/OWNERS
    - charts/ingress-nginx/changelog/*
    newRootPath: charts/ingress-nginx
    ignorePaths:
    - .kube-linter.yaml
    - Chart.yaml
    - values.schema.json
