version: 2.1
orbs:
  architect: giantswarm/architect@0.2.0

workflows:
  package-and-push-chart-on-tag:
    jobs:
      - architect/push-to-app-catalog:
          name: "package and push nginx-ingress-controller-app chart"
          app_catalog: "giantswarm-catalog"
          app_catalog_test: "giantswarm-test-catalog"
          chart: "nginx-ingress-controller-app"
          # Trigger job on git tag.
          filters:
            tags:
              only: /^v.*/
