version: 2.1
orbs:
  architect: giantswarm/architect@4.6.0

workflows:
  version: 2
  build:
    jobs:
      - architect/push-to-app-catalog:
          name: push-to-default-app-catalog
          app_catalog: "default-catalog"
          app_catalog_test: "default-test-catalog"
          chart: "nginx-ingress-controller-app"
          executor: "architect"
          persist_chart_archive: true
          filters:
            # Trigger the job also on git tag.
            tags:
              only: /^v.*/

      - architect/push-to-app-catalog:
          name: push-to-giantswarm-app-catalog
          app_catalog: "giantswarm-catalog"
          app_catalog_test: "giantswarm-test-catalog"
          chart: "nginx-ingress-controller-app"
          executor: "architect"
          filters:
            # Trigger the job also on git tag.
            tags:
              only: /^v.*/

      - architect/run-tests-with-ats:
          name: execute chart tests
          filters:
            # Do not trigger the job on merge to master.
            branches:
              ignore:
                - master
          requires:
            - push-to-default-app-catalog
