version: 2.1
orbs:
  architect: giantswarm/architect@4.33.0

workflows:
  version: 2
  build:
    jobs:
      - architect/push-to-app-catalog:
          name: push-to-giantswarm-app-catalog
          context: architect
          executor: app-build-suite
          chart: ingress-nginx
          app_catalog: giantswarm-catalog
          app_catalog_test: giantswarm-test-catalog
          persist_chart_archive: true
          push_to_oci_registry: true
          filters:
            tags:
              only: /^v.*/

      - architect/push-to-app-catalog:
          name: push-to-control-plane-app-catalog
          context: architect
          executor: app-build-suite
          chart: ingress-nginx
          app_catalog: control-plane-catalog
          app_catalog_test: control-plane-test-catalog
          persist_chart_archive: false
          push_to_oci_registry: true
          filters:
            tags:
              only: /^v.*/

      - architect/run-tests-with-ats:
          name: run-tests-with-ats
          filters:
            branches:
              ignore:
                - main
          requires:
            - push-to-giantswarm-app-catalog

      # - architect/push-to-app-collection:
      #     name: push-to-cloud-director-app-collection
      #     context: architect
      #     app_catalog: giantswarm
      #     app_name: ingress-nginx
      #     app_namespace: kube-system
      #     app_collection_repo: cloud-director-app-collection
      #     filters:
      #       branches:
      #         ignore: /.*/
      #       tags:
      #         only: /^v.*/
      #     requires:
      #       - push-to-giantswarm-app-catalog

      # - architect/push-to-app-collection:
      #     name: push-to-capa-app-collection
      #     context: architect
      #     app_catalog: giantswarm
      #     app_name: ingress-nginx
      #     app_namespace: kube-system
      #     app_collection_repo: capa-app-collection
      #     filters:
      #       branches:
      #         ignore: /.*/
      #       tags:
      #         only: /^v.*/
      #     requires:
      #       - push-to-giantswarm-app-catalog

      # - architect/push-to-app-collection:
      #     name: push-to-gcp-app-collection
      #     context: architect
      #     app_catalog: giantswarm
      #     app_name: ingress-nginx
      #     app_namespace: kube-system
      #     app_collection_repo: gcp-app-collection
      #     filters:
      #       branches:
      #         ignore: /.*/
      #       tags:
      #         only: /^v.*/
      #     requires:
      #       - push-to-giantswarm-app-catalog

      # - architect/push-to-app-collection:
      #     name: push-to-vsphere-app-collection
      #     context: architect
      #     app_catalog: giantswarm
      #     app_name: ingress-nginx
      #     app_namespace: kube-system
      #     app_collection_repo: vsphere-app-collection
      #     filters:
      #       branches:
      #         ignore: /.*/
      #       tags:
      #         only: /^v.*/
      #     requires:
      #       - push-to-giantswarm-app-catalog
