version: 2.1
orbs:
  architect: giantswarm/architect@0.15.0

jobs:
  run-perf-tests:
    machine:
      image: ubuntu-1604:201903-01
    working_directory:
      ~/nginx-ingress-controller-app
    steps:
      - checkout
      - run: pyenv versions
      - run: pyenv global 3.7.0
      - run: python --version
      - run: pip install pipenv aws-shell
      - run: curl -Lo /tmp/kind "https://github.com/kubernetes-sigs/kind/releases/download/v0.7.0/kind-$(uname)-amd64"
      - run: chmod +x /tmp/kind
      - run: curl -Lo /tmp/helm.tar.gz https://get.helm.sh/helm-v2.16.5-linux-amd64.tar.gz
      - run: tar zxf /tmp/helm.tar.gz -C /tmp && mv /tmp/linux-amd64/helm /tmp/helm
      - run: /tmp/helm init -c
      - run: curl -Lo /tmp/kind-app-testing.sh -q https://raw.githubusercontent.com/giantswarm/kube-app-testing/v0.5.2/kube-app-testing.sh
      - run: chmod +x /tmp/kind-app-testing.sh
      - run: curl -Lo /tmp/kubectl https://storage.googleapis.com/kubernetes-release/release/v1.18.0/bin/linux/amd64/kubectl
      - run: chmod +x /tmp/kubectl
      - run: PATH="/tmp:$PATH" kind-app-testing.sh -c ${CIRCLE_PROJECT_REPONAME} -t giantswarm --cluster-name ci-${CIRCLE_PROJECT_REPONAME} -n kube-system -a ${GS_API_KEY} -r ${GS_RELEASE} --availability-zone ${GS_AVAILABILITY_ZONE} --giantswarm-api-url ${GS_API_URL} --min-scaling 3 --max-scaling 3
      - store_test_results:
          path: test-results
      - store_artifacts:
          path: test-results
      - run:
          name: Cleanup resources
          command: PATH="/tmp:$PATH" kind-app-testing.sh -a ${GS_API_KEY} --force-cleanup
          when: on_fail

workflows:
  version: 2
  build:
    jobs:
      - architect/push-to-app-catalog:
          name: push-to-default-app-catalog
          app_catalog: "default-catalog"
          app_catalog_test: "default-test-catalog"
          chart: "nginx-ingress-controller-app"
          filters:
            # Trigger the job also on git tag.
            tags:
              only: /^v.*/

      - architect/push-to-app-catalog:
          name: push-to-giantswarm-app-catalog
          app_catalog: "giantswarm-catalog"
          app_catalog_test: "giantswarm-test-catalog"
          chart: "nginx-ingress-controller-app"
          filters:
            # Trigger the job also on git tag.
            tags:
              only: /^v.*/

      - architect/push-to-app-catalog:
          name: push-to-control-plane-app-catalog-master
          app_catalog: "control-plane-catalog"
          app_catalog_test: "control-plane-test-catalog"
          chart: "nginx-ingress-controller-app"
          filters:
            branches:
              only: master
            tags:
              only: /^v.*/

      - architect/push-to-app-catalog:
          name: push-to-control-plane--app-catalog-pr
          app_catalog: "control-plane-catalog"
          app_catalog_test: "control-plane-test-catalog"
          chart: "nginx-ingress-controller-app"
          filters:
            branches:
              ignore: master

      - architect/push-to-app-collection:
          name: push-to-aws-app-collection
          app_name: "nginx-ingress-controller-app"
          app_collection_repo: "aws-app-collection"
          unique: "true"
          requires:
            - push-to-control-plane-app-catalog-master
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v.*/

      - architect/push-to-app-collection:
          name: push-to-azure-app-collection
          app_name: "nginx-ingress-controller-app"
          app_collection_repo: "azure-app-collection"
          unique: "true"
          requires:
            - push-to-control-plane-app-catalog-master
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v.*/

      - architect/push-to-app-collection:
          name: push-to-kvm-app-collection
          app_name: "nginx-ingress-controller-app"
          app_collection_repo: "kvm-app-collection"
          unique: "true"
          requires:
            - push-to-control-plane-app-catalog-master
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v.*/

      - architect/integration-test:
          context: architect
          name: basic-integration-test
          test-dir: "integration/test/basic"
          filters:
            # Do not trigger the job on merge to master.
            branches:
              ignore:
                - master
          requires:
            - push-to-default-app-catalog
            - push-to-giantswarm-app-catalog
            - push-to-control-plane-app-catalog-master

      # Require manual approval for running performance tests.
      - hold-run-perf-tests:
          type: approval
          filters:
            # Do not trigger the job on master branch or release tags.
            branches:
              ignore:
                - master
            tags:
              ignore: /^v.*/

      - run-perf-tests:
          requires:
            - hold-run-perf-tests
            - basic-integration-test
          filters:
            # Do not trigger the job on master branch or release tags.
            branches:
              ignore:
                - master
            tags:
              ignore: /^v.*/
