version: 2.1
orbs:
  architect: giantswarm/architect@4.8.0

workflows:
  version: 2
  build:
    jobs:
      - architect/push-to-app-catalog:
          name: push-to-giantswarm-app-catalog
          app_catalog: "giantswarm-catalog"
          app_catalog_test: "giantswarm-test-catalog"
          chart: "nginx-ingress-controller-app"
          executor: "app-build-suite"
          persist_chart_archive: true
          filters:
            # Trigger the job also on git tag.
            tags:
              only: /^v.*/

      - architect/run-tests-with-ats:
          name: execute chart tests
          filters:
            # Do not trigger the job on merge to master.
            branches:
              ignore:
                - master
          requires:
            - push-to-giantswarm-app-catalog

      # Require manual approval for running upgrade tests.
      - hold-upgrade-tests:
          name: hold upgrade tests
          type: approval
          filters:
            # Do not trigger the job on master branch or release tags.
            branches:
              ignore:
                - master
            tags:
              ignore: /^v.*/

      - architect/run-tests-with-ats:
          name: execute upgrade tests
          additional_app-test-suite_flags: "--steps upgrade"
          filters:
            # Do not trigger the job on merge to master.
            branches:
              ignore:
                - master
          requires:
            - hold upgrade tests
            - push-to-giantswarm-app-catalog
