version: 2.1
orbs:
  architect: giantswarm/architect@dev:catalogbot-ssh

workflows:
  version: 2
  build:
    jobs:
      - architect/push-to-app-catalog:
          name: push-to-default-app-catalog
          app_catalog: "default-catalog"
          app_catalog_test: "default-test-catalog"
          chart: "nginx-ingress-controller-app"
          executor: "app-build-suite"
          filters:
            # Trigger the job also on git tag.
            tags:
              only: /^v.*/

      - architect/push-to-app-catalog:
          name: push-to-giantswarm-app-catalog
          app_catalog: "giantswarm-catalog"
          app_catalog_test: "giantswarm-test-catalog"
          chart: "nginx-ingress-controller-app"
          executor: "app-build-suite"
          filters:
            # Trigger the job also on git tag.
            tags:
              only: /^v.*/

      - architect/run-tests-with-abs:
          chart_dir: ./helm/nginx-ingress-controller-app
          name: execute chart tests
          filters:
            # Do not trigger the job on merge to master.
            branches:
              ignore:
                - master
          requires:
            - push-to-default-app-catalog
            - push-to-giantswarm-app-catalog
