version: 2.1

orbs:
  architect: giantswarm/architect@5.10.1

workflows:
  build:
    jobs:
      - architect/push-to-app-catalog:
          name: push-to-giantswarm-catalog
          context: architect
          executor: app-build-suite
          chart: ingress-nginx
          app_catalog: giantswarm-catalog
          app_catalog_test: giantswarm-test-catalog
          persist_chart_archive: true
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore:
                - main
                - master

      - architect/push-to-app-catalog:
          name: push-to-control-plane-catalog
          context: architect
          executor: app-build-suite
          chart: ingress-nginx
          app_catalog: control-plane-catalog
          app_catalog_test: control-plane-test-catalog
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore:
                - main
                - master

      - architect/run-tests-with-ats:
          name: run-tests-with-ats
          requires:
            - push-to-giantswarm-catalog
          filters:
            branches:
              ignore:
                - main

      - architect/push-to-app-collection:
          name: push-to-capa-app-collection
          context: architect
          app_catalog: control-plane-catalog
          app_name: ingress-nginx
          app_namespace: kube-system
          app_collection_repo: capa-app-collection
          requires:
            - push-to-control-plane-catalog
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v.*/

      - architect/push-to-app-collection:
          name: push-to-capz-app-collection
          context: architect
          app_catalog: control-plane-catalog
          app_name: ingress-nginx
          app_namespace: kube-system
          app_collection_repo: capz-app-collection
          requires:
            - push-to-control-plane-catalog
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v.*/

      - architect/push-to-app-collection:
          name: push-to-gcp-app-collection
          context: architect
          app_catalog: control-plane-catalog
          app_name: ingress-nginx
          app_namespace: kube-system
          app_collection_repo: gcp-app-collection
          requires:
            - push-to-control-plane-catalog
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v.*/

      - architect/push-to-app-collection:
          name: push-to-cloud-director-app-collection
          context: architect
          app_catalog: control-plane-catalog
          app_name: ingress-nginx
          app_namespace: kube-system
          app_collection_repo: cloud-director-app-collection
          requires:
            - push-to-control-plane-catalog
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v.*/

      - architect/push-to-app-collection:
          name: push-to-vsphere-app-collection
          context: architect
          app_catalog: control-plane-catalog
          app_name: ingress-nginx
          app_namespace: kube-system
          app_collection_repo: vsphere-app-collection
          requires:
            - push-to-control-plane-catalog
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v.*/
