version: 2.1

orbs:
  architect: giantswarm/architect@4.33.1

workflows:
  build:
    jobs:
      - architect/push-to-app-catalog:
          name: push-to-giantswarm-catalog
          context: architect
          executor: app-build-suite
          chart: ingress-nginx
          app_catalog: giantswarm-catalog
          app_catalog_test: giantswarm-test-catalog
          persist_chart_archive: true
          filters:
            tags:
              only: /^v.*/

      - architect/push-to-app-catalog:
          name: push-to-control-plane-catalog
          context: architect
          executor: app-build-suite
          chart: ingress-nginx
          app_catalog: control-plane-catalog
          app_catalog_test: control-plane-test-catalog
          filters:
            tags:
              only: /^v.*/

      - architect/run-tests-with-ats:
          name: run-tests-with-ats
          filters:
            branches:
              ignore:
                - main
          requires:
            - push-to-giantswarm-catalog
