version: 2.1
orbs:
  architect: giantswarm/architect@4.9.0

jobs:
  run-tests-with-k8s-version:
    parameters:
      kind_image:
        description: "kindest/node image to use for kind cluster"
        type: string
        default: "kindest/node:v1.21.2@sha256:9d07ff05e4afefbba983fac311807b3c17a5f36e7061f6cb7e2ba756255b2be4"
    machine:
      image: ubuntu-2004:202010-01
    resource_class: medium
    steps:
      - checkout
      - run:
          name: "Augment kind config file"
          command: |
            set -x

            sed -i "s|image: .*$|image: << parameters.kind_image >>|" tests/kind_config.yaml
      - architect/run-tests-with-ats:
          app-test-suite_version: "v0.2.2"
          app-test-suite_container_tag: "0.2.2"

workflows:
  version: 2
  build:
    jobs:
      - architect/push-to-app-catalog:
          name: push-to-giantswarm-app-catalog
          app_catalog: "giantswarm-catalog"
          app_catalog_test: "giantswarm-test-catalog"
          chart: "nginx-ingress-controller-app"
          executor: "app-build-suite"
          persist_chart_archive: true
          filters:
            # Trigger the job also on git tag.
            tags:
              only: /^v.*/

      # deploy to openstack installations (only tags)
      - architect/push-to-app-collection:
          name: push-to-openstack-app-collection
          app_name: "nginx-ingress-controller-app"
          app_namespace: "kube-system"
          app_catalog: "giantswarm"
          app_collection_repo: "openstack-app-collection"
          requires:
            - push-to-giantswarm-app-catalog
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v.*/

      - run-tests-with-k8s-version:
         name: execute chart tests on 1.21
         kind_image: "kindest/node:v1.21.1@sha256:69860bda5563ac81e3c0057d654b5253219618a22ec3a346306239bba8cfa1a6"
         filters:
           # Do not trigger the job on merge to master.
           branches:
             ignore:
               - master
         requires:
           - push-to-giantswarm-app-catalog

      - run-tests-with-k8s-version:
          name: execute chart tests on 1.22
          kind_image: "kindest/node:v1.22.4@sha256:ca3587e6e545a96c07bf82e2c46503d9ef86fc704f44c17577fca7bcabf5f978"
          filters:
            # Do not trigger the job on merge to master.
            branches:
              ignore:
                - master
          requires:
            - push-to-giantswarm-app-catalog

      - run-tests-with-k8s-version:
         name: execute chart tests on 1.23
         kind_image: "kindest/node:v1.23.1@sha256:355a1e3b7b0fe315c896f63a73847c554aac8fb8615c6bf47f1ca303009e9a2d"
         filters:
           # Do not trigger the job on merge to master.
           branches:
             ignore:
               - master
         requires:
           - push-to-giantswarm-app-catalog
