{{- if .Values.controller.admissionWebhooks.enabled -}}
# before changing this value, check the required kubernetes version
# https://kubernetes.io/docs/reference/access-authn-authz/extensible-admission-controllers/#prerequisites
apiVersion: admissionregistration.k8s.io/v1beta1
kind: ValidatingWebhookConfiguration
metadata:
  name: {{ include "resource.default.name" . }}-admission
  labels:
    {{- include "labels.common" . | nindent 4 }}
    app.kubernetes.io/component: admission-webhook
webhooks:
- name: validate.nginx.ingress.kubernetes.io
  rules:
  - apiGroups:
    - extensions
    - networking.k8s.io
    apiVersions:
    - v1beta1
    operations:
    - CREATE
    - UPDATE
    resources:
    - ingresses
  failurePolicy: Fail
  sideEffects: None
  admissionReviewVersions:
    - v1
    - v1beta1
  clientConfig:
    service:
      namespace: {{ .Release.Namespace }}
      name: {{ include "resource.default.name" . }}-admission
      path: /extensions/v1beta1/ingresses
{{- end }}
