{{- if .Values.controller.admissionWebhooks.enabled -}}
# before changing this value, check the required kubernetes version
# https://kubernetes.io/docs/reference/access-authn-authz/extensible-admission-controllers/#prerequisites
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: {{ include "ingress-nginx.fullname" . }}-admission
  labels:
    {{- include "labels.common" . | nindent 4 }}
    app.kubernetes.io/component: admission-webhook
webhooks:
- name: validate.nginx.ingress.kubernetes.io
  rules:
  - apiGroups:
    - networking.k8s.io
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    resources:
    - ingresses
  failurePolicy: {{ .Values.controller.admissionWebhooks.failurePolicy | default "Fail" }}
  sideEffects: None
  admissionReviewVersions:
    - v1
  clientConfig:
    service:
      namespace: {{ .Release.Namespace }}
      name: {{ include "ingress-nginx.fullname" . }}-admission
      path: /networking/v1/ingresses
  {{- if .Values.controller.admissionWebhooks.timeoutSeconds }}
  timeoutSeconds: {{ .Values.controller.admissionWebhooks.timeoutSeconds }}
  {{- end }}
{{- end }}
