configmap:
  worker-processes: "2"
controller:
  name: nginx-ingress-controller
  autoscaling:
    enabled: false
  service:
    enabled: true
    nodePorts:
      http: 30010
      https: 30011
profile: xxs
