apiVersion: v1
appVersion: v0.44.0
description: A Helm chart for the nginx ingress-controller
home: https://github.com/giantswarm/nginx-ingress-controller-app
icon: https://s.giantswarm.io/app-icons/1/png/nginx-ingress-controller-app-light.png
kubeVersion: ">=1.16.0-0"
name: nginx-ingress-controller-app
version: [[ .Version ]]
annotations:
  application.giantswarm.io/values-schema: https://raw.githubusercontent.com/giantswarm/nginx-ingress-controller-app/v[[ .Version ]]/helm/nginx-ingress-controller-app/values.schema.json
  application.giantswarm.io/readme: https://raw.githubusercontent.com/giantswarm/nginx-ingress-controller-app/v[[ .Version ]]/README.md
