# Default values for nginx-ingress-controller-app.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

namespace: kube-system

# baseDomain is a dynamic value, it comes from the cluster values configmap and applies only to Giant Swarm clusters.
# applies only to Giant Swarm clusters
baseDomain: uun5a.k8s.ginger.eu-central-1.aws.gigantic.io
# clusterID is dynamic environment value, calculated after cluster creation
# applies only to Giant Swarm clusters
clusterID: uun5a
# provider is dynamic environment value, which comes from application catalog configuration
# applies only to Giant Swarm clusters
provider: kvm
# ingressController is dynamic environment value, which comes from application catalog configuration
# applies only to Giant Swarm clusters
ingressController:
  legacy: false
  replicas: 3

# configmap contains settings that can be overridden with a custom values
# configmap.
configmap:
  disable-access-log: "false"
  enable-vts-status: "true"
  error-log-level: "error"
  hsts: "false"
  server-name-hash-bucket-size: "1024"
  server-name-hash-max-size: "1024"
  server-tokens: "false"
  worker-processes: "4"
  use-forwarded-headers: "true"

  # optional settings that can be set.
  enable-underscores-in-headers: ""
  http-snippet: ""
  http2-max-field-size: ""
  large-client-header-buffers: ""
  log-format-upstream: ""
  proxy-buffers-size: ""
  proxy-buffers: ""
  use-proxy-protocol: ""
  vts-default-filter-key: ""
  
  # optional hpa settings
  hpa-enabled: false
  hpa-min-replicas: 2
  hpa-max-replicas: 11
  hpa-target-cpu-utilization-percentage: 50
  hpa-target-memory-utilization-percentage: 50

  # command args options
  annotations-prefix: nginx.ingress.kubernetes.io
  default-ssl-certificate: ""
  ingress-class: nginx

controller:
  name: nginx-ingress-controller
  k8sAppLabel: nginx-ingress-controller
  metricsPort: 10254

  maxUnavailable: 1

  configmap:
    name: ingress-nginx

  image:
    repository: giantswarm/nginx-ingress-controller
    tag: 0.26.1

  rbac:

  role:
    name: nginx-ingress-role

  service:
    enabled: true
    # type applies only to AWS provider:
    # - external (default)
    # - internal
    # ...
    type: external
    # Sets the NodePorts that maps to the Ingress' ports 80 (http) and 443 (https).
    # nodePort service type is not created for AWS provider as LoadBalancer is used there.
    nodePorts:
      http: 30010
      https: 30011

  resources:
    requests:
      cpu: 500m
      memory: 600Mi

  userID: 33
  groupID: 33

defaultBackend:
  name: default-http-backend
  k8sAppLabel: default-http-backend
  port: 8080

  replicas: 2

  image:
    repository: giantswarm/defaultbackend
    tag: 1.2

  resources:
    limits:
      cpu: 10m
      memory: 20Mi
    requests:
      cpu: 10m
      memory: 20Mi

  userID: 33
  groupID: 33

image:
  registry: quay.io

global:
  controller:
    tempReplicas: 2
    useProxyProtocol: false
  migration:
    enabled: false

test:
  image:
    registry: quay.io
    repository: giantswarm/alpine-testing
    tag: 0.1.0
