# Default values for nginx-ingress-controller-app.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# baseDomain is a dynamic value, it comes from the cluster values configmap
# applies only to Giant Swarm clusters
baseDomain: uun5a.k8s.ginger.eu-central-1.aws.gigantic.io
# clusterID is dynamic environment value, calculated after cluster creation
# applies only to Giant Swarm clusters
clusterID: uun5a
# provider is dynamic environment value, which comes from application catalog configuration
# applies only to Giant Swarm clusters
provider: kvm
# ingressController is dynamic environment value, which comes from application catalog configuration
# applies only to Giant Swarm clusters
ingressController:
  legacy: false

# for all the nginx configmap config options see https://github.com/kubernetes/ingress-nginx/blob/master/docs/user-guide/nginx-configuration/configmap.md#configmaps
configmap:
  error-log-level: "error"
  # Disables setting a 'Strict-Transport-Security' header, which can be harmful.
  # See https://github.com/kubernetes/ingress-nginx/issues/549#issuecomment-291894246
  hsts: "false"
  # Increase hash table size to allow more server names for stability reasons
  server-name-hash-bucket-size: "1024"
  server-tokens: "false"
  worker-processes: "1"
  use-forwarded-headers: "true"

controller:
  name: nginx-ingress-controller
  k8sAppLabel: nginx-ingress-controller

  replicaCount: 1

  maxUnavailable: 1

  configmap:
    name: ingress-nginx

  image:
    repository: giantswarm/nginx-ingress-controller
    # when updating tag make sure to also keep appVersion in Chart.yaml in sync
    tag: 0.29.0

  rbac:

  role:
    name: nginx-ingress-role

  service:
    enabled: false
    # type applies only to AWS provider:
    # - external (default)
    # - internal
    # ...
    type: external
    # Sets the NodePorts that maps to the Ingress' ports 80 (http) and 443 (https).
    # nodePort service type is not created for AWS provider as LoadBalancer is used there.
    nodePorts:
      http: 30010
      https: 30011

  metrics:
    enabled: false
    port: 10254

    service:
      servicePort: 9913

  resources:
    requests:
      cpu: 2
      memory: 2.5Gi

  # optional hpa settings
  autoscaling:
    enabled: true
    minReplicas: 1
    maxReplicas: 20
    targetCPUUtilizationPercentage: 50
    targetMemoryUtilizationPercentage: 50

  # command args options
  annotationsPrefix: nginx.ingress.kubernetes.io
  defaultSSLCertificate: ""
  ingressClass: nginx

  # www-data -> uid 101
  userID: 101
  groupID: 101

image:
  registry: quay.io

test:
  image:
    registry: quay.io
    repository: giantswarm/alpine-testing
    tag: 0.1.0
