kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: {{ include "ingress-nginx.fullname" . }}-admission
  namespace: {{ .Release.Namespace }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
  labels:
    {{- include "ingress-nginx.labels" . | nindent 4 }}
    app.kubernetes.io/component: admission-webhook
spec:
  podSelector:
    matchLabels:
      {{- include "ingress-nginx.labels" . | nindent 6 }}
      app.kubernetes.io/component: admission-webhook
  egress:
  - {}
  policyTypes:
  - Egress
  - Ingress
  
