kind: ConfigMap
apiVersion: v1
metadata:
  name: {{ .Values.controller.configmap.name }}
  namespace: {{ .Release.Namespace }}
  labels:
    giantswarm.io/service-type: "managed"
    k8s-addon: ingress-nginx.addons.k8s.io
data:
  {{- toYaml .Values.configmap | trim | nindent 2 }}
