kind: ConfigMap
apiVersion: v1
metadata:
  name: {{ include "resource.default.name" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "labels.common" . | nindent 4 }}
data:
  {{- toYaml .Values.configmap | trim | nindent 2 }}
