{{- if .Values.controller.service.internal.enabled }}
apiVersion: v1
kind: Service
metadata:
  annotations:
  {{- if .Values.controller.service.externalDNS.enabled }}
    external-dns.alpha.kubernetes.io/hostname: {{ .Values.controller.service.internal.subdomain }}.{{ .Values.baseDomain }}
  {{- end }}
  {{- if eq .Values.controller.service.internal.type "LoadBalancer" }}
  {{- if eq .Values.provider "aws" }}
    service.beta.kubernetes.io/aws-load-balancer-internal: 0.0.0.0/0
    {{- if index .Values.configmap "use-proxy-protocol" }}
    service.beta.kubernetes.io/aws-load-balancer-proxy-protocol: '*'
    {{- end }}
    service.beta.kubernetes.io/aws-load-balancer-cross-zone-load-balancing-enabled: "true"
  {{- else if eq .Values.provider "azure" }}
    # this annotation adds lb rules for both TCP and UDP to allow UDP outbound connection with Standard LB
    service.beta.kubernetes.io/azure-load-balancer-mixed-protocols: "true"
    service.beta.kubernetes.io/azure-load-balancer-internal: "true"
  {{- end }}
  {{- end }}
  name: {{ include "resource.default.name" . }}-internal
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "labels.common" . | nindent 4 }}
    app.kubernetes.io/component: controller
spec:
  type: {{ .Values.controller.service.internal.type }}
  {{- if eq .Values.controller.service.internal.type "LoadBalancer" }}
  loadBalancerSourceRanges:
  - 0.0.0.0/0
  {{- end }}
  ports:
  - name: http
    port: {{ .Values.controller.service.internal.ports.http }}
    protocol: TCP
    targetPort: {{ .Values.controller.service.targetPorts.http }}
    {{- if eq .Values.controller.service.internal.type "NodePort" }}
    nodePort: {{ .Values.controller.service.internal.nodePorts.http }}
    {{- end }}
  - name: https
    port: {{ .Values.controller.service.internal.ports.https }}
    protocol: TCP
    targetPort: {{ .Values.controller.service.targetPorts.https }}
    {{- if eq .Values.controller.service.internal.type "NodePort" }}
    nodePort: {{ .Values.controller.service.internal.nodePorts.https }}
    {{- end }}
  selector:
    {{- include "labels.selector" . | nindent 4 }}
  {{- if .Values.controller.service.internal.externalTrafficPolicy }}
  externalTrafficPolicy: {{ .Values.controller.service.internal.externalTrafficPolicy }}
  {{- end }}
{{- end }}
