{{- if .Values.controller.service.enabled }}
apiVersion: v1
kind: Service
metadata:
  annotations:
    prometheus.io/scheme: http
    prometheus.io/scrape: 'true'
    prometheus.io/port: '{{ .Values.controller.metrics.port }}'
  name: {{ .Values.controller.name }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Values.controller.name }}-nodeport
    giantswarm.io/service-type: "managed"
    k8s-app: {{ .Values.controller.k8sAppLabel }}
spec:
  type: NodePort
  ports:
  - name: http
    port: 80
    nodePort: {{ .Values.controller.service.nodePorts.http }}
    protocol: TCP
    targetPort: 80
  - name: https
    port: 443
    nodePort: {{ .Values.controller.service.nodePorts.https }}
    protocol: TCP
    targetPort: 443
  selector:
    k8s-app: {{ .Values.controller.k8sAppLabel }}
  {{- if .Values.controller.service.externalTrafficPolicy }}
  externalTrafficPolicy: {{ .Values.controller.service.externalTrafficPolicy }}
  {{- end }}
{{-  end }}
