{{- if .Values.provider }}
{{- if and (not .Values.ingressController.legacy) ( eq .Values.provider "azure" ) }}
apiVersion: v1
kind: Service
metadata:
  annotations:
    external-dns.alpha.kubernetes.io/hostname: ingress.{{ .Values.baseDomain }}
    # this annotation adds lb rules fot both TCP and UDP to allow UDP outbound connection with Standard LB
    service.beta.kubernetes.io/azure-load-balancer-mixed-protocols: "true"
    {{ if eq .Values.controller.service.type "internal" }}
    service.beta.kubernetes.io/azure-load-balancer-internal: "true"
    {{- end }}
  name: {{ .Values.controller.name }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Values.controller.name }}
    giantswarm.io/service-type: "managed"
    k8s-app: {{ .Values.controller.k8sAppLabel }}
spec:
  type: LoadBalancer
  loadBalancerSourceRanges:
  - 0.0.0.0/0
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 80
  - name: https
    port: 443
    protocol: TCP
    targetPort: 443
  selector:
    k8s-app: {{ .Values.controller.k8sAppLabel }}
  {{- if eq .Values.controller.service.externalTrafficPolicy }}
  externalTrafficPolicy: {{ .Values.controller.service.externalTrafficPolicy }}
  {{- end }}
{{- end }}
{{- end }}
