{{- if .Values.controller.metrics.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.controller.name }}-monitoring
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Values.controller.name }}
    giantswarm.io/service-type: "managed"
    app.kubernetes.io/name: {{ .Values.controller.k8sAppLabel }}
spec:
  clusterIP: None
  ports:
  - name: metrics
    port: {{ .Values.controller.metrics.service.servicePort }}
    targetPort: metrics
  selector:
    app.kubernetes.io/name: {{ .Values.controller.k8sAppLabel }}
{{-  end }}
