{{- if .Values.controller.admissionWebhooks.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "ingress-nginx.fullname" . }}-admission
  namespace: {{ .Release.Namespace }}
{{- if .Values.controller.admissionWebhooks.service.annotations }}
  annotations: {{ toYaml .Values.controller.admissionWebhooks.service.annotations | nindent 4 }}
{{- end }}
  labels:
    {{- include "ingress-nginx.labels" . | nindent 4 }}
spec:
  type: {{ .Values.controller.admissionWebhooks.service.type }}
  ports:
    - name: https-webhook
      port: 443
      targetPort: webhook
  selector:
    {{- include "labels.selector" . | nindent 4 }}
{{- end }}
