{{- if .Values.controller.metrics.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "ingress-nginx.fullname" . }}-monitoring
  namespace: {{ .Release.Namespace }}
  annotations:
    giantswarm.io/monitoring-path: /metrics
    giantswarm.io/monitoring-port: {{ .Values.controller.metrics.port | quote }}
    giantswarm.io/monitoring-app-label: {{ .Chart.Name | quote }}
    prometheus.io/port: {{ .Values.controller.metrics.port | quote }}
    prometheus.io/scrape: "true"
  labels:
    {{- include "ingress-nginx.labels" . | nindent 4 }}
    app.kubernetes.io/component: controller
    giantswarm.io/monitoring: "true"
  {{- if .Values.controller.metrics.service.labels }}
    {{- toYaml .Values.controller.metrics.service.labels | nindent 4 }}
  {{- end }}
spec:
  clusterIP: None
  ports:
  - name: metrics
    port: {{ .Values.controller.metrics.service.servicePort }}
    protocol: TCP
    targetPort: metrics
  selector:
    {{- include "ingress-nginx.selectorLabels" . | nindent 4 }}
{{- end }}
