{{- if .Values.controller.service.enabled }}
apiVersion: v1
kind: Service
metadata:
  annotations:
  {{- range $key, $value := .Values.controller.service.annotations }}
    {{ $key }}: {{ $value | quote }}
  {{- end }}
  {{- if and .Values.controller.service.externalDNS.enabled .Values.baseDomain }}
    external-dns.alpha.kubernetes.io/hostname: "{{ .Values.controller.service.subdomain }}.{{ .Values.baseDomain }}"
    {{- if .Values.controller.service.externalDNS.annotation }}
    {{ .Values.controller.service.externalDNS.annotation }}
    {{- end }}
  {{- end }}
  {{- if eq .Values.controller.service.type "LoadBalancer" }}
  {{- if or (eq .Values.provider "aws") (eq .Values.provider "capa") }}
    {{- if not .Values.controller.service.public }}
    service.beta.kubernetes.io/aws-load-balancer-internal: "true"
    service.beta.kubernetes.io/aws-load-balancer-scheme: "internal"
    {{- end }}
    {{- if ne (index .Values.configmap "use-proxy-protocol") "false" }}
    service.beta.kubernetes.io/aws-load-balancer-proxy-protocol: "*"
    {{- end }}
    service.beta.kubernetes.io/aws-load-balancer-cross-zone-load-balancing-enabled: "true"
  {{- else if eq .Values.provider "azure" }}
    # this annotation adds lb rules for both TCP and UDP to allow UDP outbound connection with Standard LB
    service.beta.kubernetes.io/azure-load-balancer-mixed-protocols: "true"
    {{- if not .Values.controller.service.public }}
    service.beta.kubernetes.io/azure-load-balancer-internal: "true"
    {{- end }}
  {{- end }}
  {{- end }}
  name: {{ include "resource.controller-service.name" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "ingress-nginx.labels" . | nindent 4 }}
    app.kubernetes.io/component: controller
  {{- if .Values.controller.service.labels }}
    {{- toYaml .Values.controller.service.labels | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.controller.service.type }}
  {{- with .Values.controller.service.loadBalancerSourceRanges }}
  loadBalancerSourceRanges: {{ toYaml . | nindent 2 }}
  {{- end }}
  ports:
  - name: http
    port: {{ .Values.controller.service.ports.http }}
    protocol: TCP
    targetPort: {{ .Values.controller.service.targetPorts.http }}
    {{- if eq .Values.controller.service.type "NodePort" }}
    nodePort: {{ .Values.controller.service.nodePorts.http }}
    {{- end }}
  - name: https
    port: {{ .Values.controller.service.ports.https }}
    protocol: TCP
    targetPort: {{ .Values.controller.service.targetPorts.https }}
    {{- if eq .Values.controller.service.type "NodePort" }}
    nodePort: {{ .Values.controller.service.nodePorts.https }}
    {{- end }}
  selector:
    {{- include "ingress-nginx.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: controller
  {{- if .Values.controller.service.externalTrafficPolicy }}
  externalTrafficPolicy: {{ .Values.controller.service.externalTrafficPolicy }}
  {{- end }}
{{- end }}
