{{- if and .Values.controller.service.enabled .Values.controller.service.internal.enabled}}
apiVersion: v1
kind: Service
metadata:
  annotations:
  {{- range $key, $value := .Values.controller.service.internal.annotations }}
    {{ $key }}: {{ $value | quote }}
  {{- end }}
  {{- if and .Values.controller.service.externalDNS.enabled .Values.baseDomain }}
    external-dns.alpha.kubernetes.io/hostname: "{{ .Values.controller.service.internal.subdomain }}.{{ .Values.baseDomain }}"
    {{- if .Values.controller.service.externalDNS.annotation }}
    {{ .Values.controller.service.externalDNS.annotation }}
    {{- end }}
  {{- end }}
  {{- if eq .Values.controller.service.type "LoadBalancer" }}
  {{- if or (eq .Values.provider "aws") (eq .Values.provider "capa") }}
    service.beta.kubernetes.io/aws-load-balancer-internal: "true"
    service.beta.kubernetes.io/aws-load-balancer-scheme: "internal"
    {{- if ne (index .Values.configmap "use-proxy-protocol") "false" }}
    service.beta.kubernetes.io/aws-load-balancer-proxy-protocol: "*"
    {{- end }}
    service.beta.kubernetes.io/aws-load-balancer-cross-zone-load-balancing-enabled: "true"
  {{- else if eq .Values.provider "azure" }}
    service.beta.kubernetes.io/azure-load-balancer-mixed-protocols: "true"
    service.beta.kubernetes.io/azure-load-balancer-internal: "true"
  {{- end }}
  {{- end }}
  labels:
    {{- include "ingress-nginx.labels" . | nindent 4 }}
    app.kubernetes.io/component: controller
  {{- if .Values.controller.service.labels }}
    {{- toYaml .Values.controller.service.labels | nindent 4 }}
  {{- end }}
  name: {{ include "resource.controller-service-internal.name" . }}
  namespace: {{ .Release.Namespace }}
spec:
  type: {{ .Values.controller.service.type }}
{{- if .Values.controller.service.internal.loadBalancerIP }}
  loadBalancerIP: {{ .Values.controller.service.internal.loadBalancerIP }}
{{- end }}
{{- if .Values.controller.service.internal.loadBalancerSourceRanges }}
  loadBalancerSourceRanges: {{ toYaml .Values.controller.service.internal.loadBalancerSourceRanges | nindent 4 }}
{{- end }}
{{- if .Values.controller.service.internal.externalTrafficPolicy }}
  externalTrafficPolicy: {{ .Values.controller.service.internal.externalTrafficPolicy }}
{{- end }}
  ports:
    - name: http
      port: {{ .Values.controller.service.internal.ports.http }}
      protocol: TCP
      targetPort: {{ .Values.controller.service.targetPorts.http }}
    {{- if eq .Values.controller.service.type "NodePort" }}
      nodePort: {{ .Values.controller.service.internal.nodePorts.http }}
    {{- end }}
    - name: https
      port: {{ .Values.controller.service.internal.ports.https }}
      protocol: TCP
      targetPort: {{ .Values.controller.service.targetPorts.https }}
    {{- if eq .Values.controller.service.type "NodePort" }}
      nodePort: {{ .Values.controller.service.internal.nodePorts.https }}
    {{- end }}
  selector:
    {{- include "ingress-nginx.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: controller
{{- end }}
