apiVersion: v1
kind: Service
metadata:
  name: {{ include "resource.default.name" . }}-monitoring
  namespace: {{ .Release.Namespace }}
  annotations:
    giantswarm.io/monitoring: "true"
    giantswarm.io/monitoring-path: /metrics
    giantswarm.io/monitoring-port: {{ .Values.controller.metrics.port | quote }}
  labels:
    {{- include "labels.common" . | nindent 4 }}
    giantswarm.io/monitoring: "true"
spec:
  clusterIP: None
  ports:
  - name: metrics
    port: {{ .Values.controller.metrics.service.servicePort }}
    targetPort: metrics
  selector:
    {{- include "labels.selector" . | nindent 4 }}
