{{- if or (and (gt (.Values.cluster.profile | int) 2) (and .Values.controller.autoscaling.enabled (gt (.Values.controller.autoscaling.minReplicas | int) 1))) (gt (.Values.controller.replicaCount | int) 1) }}
apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  labels:
    app: {{ .Values.controller.name }}
    giantswarm.io/service-type: "managed"
    app.kubernetes.io/name: {{ .Values.controller.k8sAppLabel }}
  name: {{ .Values.controller.name }}
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ .Values.controller.k8sAppLabel }}
  maxUnavailable: {{ .Values.controller.maxUnavailable }}
{{- end }}
