{{- if .Values.controller.service.enabled }}
apiVersion: v1
kind: Service
metadata:
  annotations:
    external-dns.alpha.kubernetes.io/hostname: {{ .Values.controller.service.subdomain }}.{{ .Values.baseDomain }}
  {{- if eq .Values.controller.service.type "LoadBalancer" }}
  {{- if eq .Values.provider "aws" }}
    {{- if not .Values.controller.service.public }}
    service.beta.kubernetes.io/aws-load-balancer-internal: 0.0.0.0/0
    {{- end }}
    {{- if index .Values.configmap "use-proxy-protocol" }}
    service.beta.kubernetes.io/aws-load-balancer-proxy-protocol: '*'
    {{- end }}
    service.beta.kubernetes.io/aws-load-balancer-cross-zone-load-balancing-enabled: "true"
  {{- else if eq .Values.provider "azure" }}
    # this annotation adds lb rules for both TCP and UDP to allow UDP outbound connection with Standard LB
    service.beta.kubernetes.io/azure-load-balancer-mixed-protocols: "true"
    {{- if not .Values.controller.service.public }}
    service.beta.kubernetes.io/azure-load-balancer-internal: "true"
    {{- end }}
  {{- end }}
  {{- end }}
  name: {{ include "resource.default.name" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "labels.common" . | nindent 4 }}
spec:
  type: {{ .Values.controller.service.type }}
  {{- if eq .Values.controller.service.type "LoadBalancer" }}
  loadBalancerSourceRanges:
  - 0.0.0.0/0
  {{- end }}
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 80
  - name: https
    port: 443
    protocol: TCP
    targetPort: 443
  selector:
    {{- include "labels.selector" . | nindent 4 }}
  {{- if .Values.controller.service.externalTrafficPolicy }}
  externalTrafficPolicy: {{ .Values.controller.service.externalTrafficPolicy }}
  {{- end }}
{{- end }}
