{{- if .Values.provider }}
{{- if eq .Values.provider "aws" }}
apiVersion: v1
kind: Service
metadata:
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-proxy-protocol: "*"
  name: {{ .Values.controller.name }}-external-lb
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.controller.name }}
    giantswarm.io/service-type: "managed"
    k8s-app: {{ .Values.controller.k8sAppLabel }}
spec:
  type: LoadBalancer
  loadBalancerSourceRanges:
  - 0.0.0.0/0
  ports:
  - name: http
    port: 80
    nodePort: {{ .Values.controller.service.nodePorts.http }}
    protocol: TCP
    targetPort: 80
  - name: https
    port: 443
    nodePort: {{ .Values.controller.service.nodePorts.https }}
    protocol: TCP
    targetPort: 443
  selector:
    k8s-app: {{ .Values.controller.k8sAppLabel }}
{{- end }}
{{- end }}
