kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: {{ include "resource.default.name" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: nginx-ingress-controller
    {{- include "labels.common" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      {{- include "labels.selector" . | nindent 6 }}
  ingress:
  - ports:
    {{- range $key, $value := .Values.controller.containerPort }}
    - port: {{ $value }}
      protocol: TCP
    {{- end }}
    {{- if .Values.controller.admissionWebhooks.enabled }}
    - port: {{ .Values.controller.admissionWebhooks.port }}
      protocol: TCP
    {{- end }}
    - port: {{ .Values.controller.metrics.port }}
      protocol: TCP
  egress:
  - {}
  policyTypes:
  - Egress
  - Ingress

