{{- if (semverCompare "<1.25.0-0" .Capabilities.KubeVersion.Version) }}
{{- if .Values.podSecurityPolicy.enabled -}}
apiVersion: policy/v1beta1
kind: PodSecurityPolicy
metadata:
  name: {{ include "ingress-nginx.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "ingress-nginx.labels" . | nindent 4 }}
spec:
  allowPrivilegeEscalation: true
  privileged: true
  allowedCapabilities:
  - NET_BIND_SERVICE
  runAsUser:
    rule: MustRunAs
    ranges:
      - min: 1
        max: 65535
  runAsGroup:
    rule: MustRunAs
    ranges:
      - min: 1
        max: 65535
  seLinux:
    rule: RunAsAny
  supplementalGroups:
    rule: 'MustRunAs'
    ranges:
      - min: 1
        max: 65535
  fsGroup:
    rule: 'MustRunAs'
    ranges:
      - min: 1
        max: 65535
  volumes:
  - 'secret'
  - 'configMap'
{{- end }}
{{- end }}
