apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "resource.default.name" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "labels.common" . | nindent 4 }}
  {{- if .Values.serviceAccount.annotations }}
  annotations:
  {{ toYaml .Values.serviceAccount.annotations | indent 4 }}
  {{- end }}
